"""Per-student config at ``~/.wp7/config.toml``.

Shared by all `pixi run` wrapper scripts in this directory. Keeps the
student's identity (slug, ephys account, email) out of the shared
course-materials tree so the same clone works for anyone.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ImportError:  # pragma: no cover — fallback for 3.10
    import tomli as tomllib  # type: ignore[no-redef]

CONFIG_DIR = Path.home() / ".wp7"
CONFIG_PATH = CONFIG_DIR / "config.toml"
DEFAULT_HOST = "gamma3"


@dataclass
class WP7Config:
    slug: str
    account: str
    email: str
    host: str = DEFAULT_HOST

    @property
    def hpc_path(self) -> str:
        return f"/storage2/arash/teaching/wp7/{self.slug}"


def load(required: bool = True) -> WP7Config | None:
    """Read ``~/.wp7/config.toml``.

    When ``required`` is True (default), exits with a helpful message if
    the config is missing. Set to False in scripts that can operate
    without it (e.g. setup_ssh.py *creates* the config).
    """
    if not CONFIG_PATH.is_file():
        if required:
            print(
                f"error: {CONFIG_PATH} not found.\n"
                f"run `pixi run setup-ssh` to create it, or make it manually:\n"
                f"  mkdir -p {CONFIG_DIR}\n"
                f"  cat > {CONFIG_PATH} <<EOF\n"
                f'  slug = "alice-abel"\n'
                f'  account = "ephys03"\n'
                f'  email = "alice.abel@campus.lmu.de"\n'
                f"  EOF\n",
                file=sys.stderr,
            )
            sys.exit(2)
        return None

    with CONFIG_PATH.open("rb") as f:
        data = tomllib.load(f)

    missing = [k for k in ("slug", "account", "email") if k not in data]
    if missing:
        print(f"error: {CONFIG_PATH} is missing keys: {missing}", file=sys.stderr)
        sys.exit(2)

    return WP7Config(
        slug=data["slug"],
        account=data["account"],
        email=data["email"],
        host=data.get("host", DEFAULT_HOST),
    )


def save(cfg: WP7Config) -> None:
    """Write ``~/.wp7/config.toml`` (creates the parent dir).

    Uses manual formatting — we only need four keys and no arrays,
    avoids a hard dependency on ``tomli_w``.
    """
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    body = (
        f'# WP7 per-student config. Generated by `pixi run setup-ssh`.\n'
        f'slug = "{cfg.slug}"\n'
        f'account = "{cfg.account}"\n'
        f'email = "{cfg.email}"\n'
        f'host = "{cfg.host}"\n'
    )
    CONFIG_PATH.write_text(body)
    # Restrict permissions — contains nothing sensitive but still personal.
    try:
        os.chmod(CONFIG_PATH, 0o600)
    except OSError:
        pass


def summary(cfg: WP7Config) -> str:
    return (
        f"  slug:    {cfg.slug}\n"
        f"  account: {cfg.account}\n"
        f"  email:   {cfg.email}\n"
        f"  host:    {cfg.host}\n"
        f"  hpc:     {cfg.hpc_path}\n"
    )
